name: Build & Test on push and open PR

on:
  push:
    branches: ["main", "build/feature-login"]
  pull_request:
    branches: ["main", "build/feature-login"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew test
